apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik-talos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-talos
  template:
    metadata:
      labels:
        app: traefik-talos
    spec:
      serviceAccountName: traefik-talos
      containers:
        - name: traefik
          image: traefik:v2.11
          args:
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --providers.kubernetesingress
            - --providers.kubernetesingress.ingressclass=traefik-talos
            - --api.insecure=true
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
