apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-talos
spec:
  type: LoadBalancer
  loadBalancerIP: 10.4.1.89
  allocateLoadBalancerNodePorts: true
  selector:
    app: traefik-talos
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: websecure
      port: 443
      targetPort: websecure
    - name: ssh
      port: 22
      targetPort: ssh
    - name: admin
      port: 8080
      targetPort: admin
